/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/dev/diagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/lib/geo`; params?: Router.UnknownInputParams; } | { pathname: `/modals/DistancePicker`; params?: Router.UnknownInputParams; } | { pathname: `/modals/RecyclingModal`; params?: Router.UnknownInputParams; } | { pathname: `/modals/VegetarianModal`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownOutputParams; } | { pathname: `/dev/diagnostics`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/geo`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/DistancePicker`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/RecyclingModal`; params?: Router.UnknownOutputParams; } | { pathname: `/modals/VegetarianModal`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/leaderboard${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tracker${`?${string}` | `#${string}` | ''}` | `/tracker${`?${string}` | `#${string}` | ''}` | `/dev/diagnostics${`?${string}` | `#${string}` | ''}` | `/lib/geo${`?${string}` | `#${string}` | ''}` | `/modals/DistancePicker${`?${string}` | `#${string}` | ''}` | `/modals/RecyclingModal${`?${string}` | `#${string}` | ''}` | `/modals/VegetarianModal${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tracker` | `/tracker`; params?: Router.UnknownInputParams; } | { pathname: `/dev/diagnostics`; params?: Router.UnknownInputParams; } | { pathname: `/lib/geo`; params?: Router.UnknownInputParams; } | { pathname: `/modals/DistancePicker`; params?: Router.UnknownInputParams; } | { pathname: `/modals/RecyclingModal`; params?: Router.UnknownInputParams; } | { pathname: `/modals/VegetarianModal`; params?: Router.UnknownInputParams; };
    }
  }
}
